# Generated by Django 4.0.6 on 2022-07-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default='profile_default_pic.jpg', upload_to=''),
        ),
    ]
