# Generated by Django 4.0.6 on 2022-07-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='default_cover',
            field=models.ImageField(default='default_book_pic.png', upload_to=''),
        ),
    ]
