# Generated by Django 4.0.6 on 2022-07-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_default_cover'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='default_cover',
            new_name='cover_picture',
        ),
    ]
