# Generated by Django 4.0.6 on 2022-08-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_default_cover_book_cover_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='describtion',
            field=models.TextField(verbose_name="Kitobga ta'rif"),
        ),
    ]
